### PR TITLE
Migrate examples to `src-layout`

### PR DESCRIPTION
**Pull request by chrysle**
This pull requests transfers the `src`-layout into a separate branch - this will need to be merged with the main branch regularly, preserving the layout-related changes. We'll still have to add a note to the README on `master`.

When this is approved, I'll also create a legacy table.

### CODE REVIEW

**Review by abravalheri — APPROVED** [review]
❤️

Thank you very much, @chrysle

**Comment by webknjaz** [comment]
@chrysle I have an advice for maintaining PR branches — always use forks, even if you have full upstream access. To arbitrary users, the branch list like https://github.com/pypa/sample-namespace-packages/branches/all is confusing. Moreover, when contributors fork the repo, they may get copies of those branches at the moment of forking but won't get branch updates as they are modified upstream or cleaned up, effectively leaving them with non-collected garbage in their forks.

**Comment by chrysle** [comment]
Thanks for the advice, I'll stick to this in the future (only I would have to close this because GH doesn't allow for changing PR branches, AFAIK). BTW, could you re-visit the neighbouring PR?

**Comment by webknjaz** [comment]
@chrysle yeah, no need to close. Just keep in mind for the future.

**Comment by chrysle** [comment]
@abravalheri FYI added a `.gitattributes` file to handle merge conflicts with the new branch. The legacy table now isn't correct for this branch, should I remove it or re-run the scenarios?

**Comment by abravalheri** [comment]
Hi @chrysle, the presence of the legacy table is something that depends on the README.

Previously, we had:

> If you would like to know about deprecated installation methods (e.g. via python setup.py install) or Python 2.7, please have a look at legacy_table.md.

As a nod to the historical data in the repo (e.g. maybe there is a link somewhere referencing this repo and talking about the differences between 2.7 and 3) so that we don't remove historical data and keep consistency with old references.

If that is something you removed, it might be fine to remove the file in the branch, too.

**Comment by chrysle** [comment]
> Or update the link to reference a different branch

Done!

**Pull request merged**
